COLUMN PDB_NAME FORMAT A10

SELECT r.CON_ID, p.PDB_NAME, r.SGA_BYTES, r.PGA_BYTES, r.BUFFER_CACHE_BYTES, r.SHARED_POOL_BYTES FROM V$RSRCPDBMETRIC r, CDB_PDBS p WHERE r.CON_ID = p.CON_ID;


  SELECT r.CON_ID, p.PDB_NAME, sum(r.SGA_BYTES)/1014/1024/1024 as SGA_MB,
    sum(r.PGA_BYTES)/1024/1024 as PGA_MB,
    sum(r.BUFFER_CACHE_BYTES)/1024/1024 as BUFFER_CACHE_MB,
    sum(r.SHARED_POOL_BYTES)/1024/1024 as SHARED_POOL_MB
    FROM V$RSRCPDBMETRIC r, CDB_PDBS p 
    WHERE r.CON_ID = p.CON_ID
    group by r.CON_ID, p.PDB_NAME, r.SGA_BYTES, r.BUFFER_CACHE_BYTES;

